name: Mr Steal Yo Crypto CTF

default_ecosystem: ethereum
ethereum:
  default_network: local
  local:
    default_provider: foundry

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts/contracts
    version: 4.8.0

solidity: 
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.8.0"

plugins:
  - name: vyper
  - name: solidity
  - name: foundry
